<?php
$aluno["nome"] = "luiz bernado";
$aluno["endereco"] = "Rua A";
$aluno["cidade"] = "Vanila";
$aluno["estado"] = "Maranhão";
$aluno["idade"] = "12";
$aluno["cpf"] = "000000000.32";
echo "nome : ".$aluno["nome"] ."<br>"."endereco : ". $aluno["endereco"]."<br>". "cidade : ". $aluno["cidade"]."<br>". "estado : ". $aluno["estado"] ."<br>"."idade : ".$aluno["idade"]  ."<br>"."CPF : ".$aluno["cpf"];
echo "<br>";
echo "<br>";
$aluno["nome"] = "luwin";
$aluno["endereco"] = "Rua b";
$aluno["cidade"] = "Vani";
$aluno["estado"] = "Marai";
$aluno["idade"] = "89";
$aluno["cpf"] = "002042032.32";
echo "nome : ".$aluno["nome"] ."<br>"."endereco : ". $aluno["endereco"]."<br>". "cidade : ". $aluno["cidade"]."<br>". "estado : ". $aluno["estado"] ."<br>"."idade : ".$aluno["idade"]  ."<br>"."CPF : ".$aluno["cpf"];
echo "<br>";
echo "<br>";
$aluno["nome"] = "zeca pagodin";
$aluno["endereco"] = "Rua Ae";
$aluno["cidade"] = "candede";
$aluno["estado"] = "Maracaju";
$aluno["idade"] = "80";
$aluno["cpf"] = "043028943.21";
echo "nome : ".$aluno["nome"] ."<br>"."endereco : ". $aluno["endereco"]."<br>". "cidade : ". $aluno["cidade"]."<br>". "estado : ". $aluno["estado"] ."<br>"."idade : ".$aluno["idade"]  ."<br>"."CPF : ".$aluno["cpf"];
echo "<br>";
echo "<br>";
$professor["nome"] = "jonh";
$professor["endereco"] = "Rua Rc";
$professor["cidade"] = "magalhães";
$professor["estado"] = "Marianopolis";
$professor["idade"] = "20";
$professor["cpf"] = "089043032.32";
echo "nome : ".$professor["nome"] ."<br>"."endereco : ". $professor["endereco"]."<br>". "cidade : ". $professor["cidade"]."<br>". "estado : ". $professor["estado"] ."<br>"."idade : ".$professor["idade"]  ."<br>"."CPF : ".$professor["cpf"];
echo "<br>";
echo "<br>";
$professor["nome"] = "Raix quadrado";
$professor["endereco"] = "Rua TY";
$professor["cidade"] = "Vasconcelo";
$professor["estado"] = "Pirantinga";
$professor["idade"] = "56";
$professor["cpf"] = "8909327.32";
echo "nome : ".$professor["nome"] ."<br>"."endereco : ". $professor["endereco"]."<br>". "cidade : ". $professor["cidade"]."<br>". "estado : ". $professor["estado"] ."<br>"."idade : ".$professor["idade"]  ."<br>"."CPF : ".$professor["cpf"];
echo "<br>";
echo "<br>";
$professor["nome"] = "Jack marrom";
$professor["endereco"] = "Rua luiz peixoto";
$professor["cidade"] = "jaquele";
$professor["estado"] = "Maragantuga";
$professor["idade"] = "82";
$professor["cpf"] = "980327.32";
echo "nome : ".$professor["nome"] ."<br>"."endereco : ". $professor["endereco"]."<br>". "cidade : ". $professor["cidade"]."<br>". "estado : ". $professor["estado"] ."<br>"."idade : ".$professor["idade"]  ."<br>"."CPF : ".$professor["cpf"];
echo "<br>";
echo "<br>";
$professor["nome"] = "luiz ternado";
$professor["endereco"] = "Rua AH";
$professor["cidade"] = "VanilaH";
$professor["estado"] = "Marancão";
$professor["idade"] = "89";
$professor["cpf"] = "048390.32";
echo "nome : ".$professor["nome"] ."<br>"."endereco : ". $professor["endereco"]."<br>". "cidade : ". $professor["cidade"]."<br>". "estado : ". $professor["estado"] ."<br>"."idade : ".$professor["idade"]  ."<br>"."CPF : ".$professor["cpf"];

